#!/bin/bash
echo  "Updating WhapichatPro, aguarde."
cd  ~
cd Whapichatpro
git checkout master
git pull
cd backend
npm install --force
npm run build
npx sequelize db:migrate
npx sequelize db:seed
pm2 restart all
cd  ~
cd Whapichatpro
cd frontend
npm install --force
export NODE_OPTIONS=--openssl-legacy-provider
npx update-browserslist-db@latest
npx quasar build -P -m pwa


echo  "Atualização completa!"
